# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy all project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir hatchling \
    && pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["python", "-m", "src.server"]
